name: DunningKruger
options:
  bundleIdPrefix: com.robsinclair
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
  xcodeVersion: "16.2"

targets:
  DunningKruger:
    type: application
    platform: [iOS, macOS]
    sources:
      - DunningKruger
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.robsinclair.DunningKruger
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Kreugerizer-5000"
      configs:
        debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO
        release:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
